### PR TITLE
Report correct player limit

### PR DESCRIPTION
**Pull request by rcelyte**
Use `UnifiedNetworkPlayerModel` to get the actual player limit instead of the requested one.

127 player room, without patch:
before

with patch:
after

Tested on my WIP self-hosted master server

### CODE REVIEW

**Comment by roydejong** [comment]
Thanks, I appreciate the PR.

Could you please clarify the following:

As I understand it, the `GameplayServerConfiguration` in `UnifiedNetworkPlayerModel` is derived from the pre-connect info sent by the master server. So:

1. What scenario does this fix exactly? At least as of v1-rewrite, the server browser will always use the master server's reported maxPlayerCount and the session value is *only* used if you've created the server (if you are party leader on join).
2. I don't think this PR would work for Official Servers:  Your master server presumably sends this correctly, so does BeatTogether for example, but unfortunately official servers will sometimes send higher player counts than the host requested, which is why I'm using the session value.

**Comment by rcelyte** [comment]
> official servers will sometimes send higher player counts than the host requested

Which would be the correct value, would it not?

When my master server receives a `ConnectToServerRequest`, I'm able to send back a `ConnectToServerResponse` specifying a different value for `configuration.maxPlayerCount`. The game appears to use this returned value, noting how both screenshots show 127 platforms instead of 2.

**Comment by rcelyte** [comment]
small note: the screenshots are from an equivalent change on the master branch (using `UnifiedNetworkPlayerModel.configuration.maxPlayerCount` in the `SessionManager.connectedEvent` handler). I have no idea how to compile the `v1-rewrite` branch.

**Comment by rcelyte** [comment]
Also, do the official servers *always* return the wrong value? It reported correctly when I did a test there.

**Comment by roydejong** [comment]
> I also noticed that the number displayed on the website caps out at 5, regardless of player limit.

I've gone ahead and removed that limitation from the API altogether: https://github.com/roydejong/bssb.app/commit/cb497cfa4c336f7b2a4bd8733cbc19901c91742f

Previously a game would have to be detected as "moddded" before a higher player count was permitted, but the mod landscape is clearly changing a bit so I think it's best to remove the limitation at this point.

**Comment by rcelyte** [comment]
Wait no, it actually just creates a 5 player room when you request a 2 player one if the toggle is enabled.
room

**Comment by rcelyte** [comment]
cool.
bigroom

**Comment by rcelyte** [comment]
Alright, I managed to build the `v1-rewrite` branch. I can now confirm that this PR fixes both custom *and* official player limits.
Still not quite sure why I see 5 platforms though...

**Comment by roydejong** [comment]
> Wait no, it actually just creates a 5 player room when you request a 2 player one if the toggle is enabled. 
> I think it's an issue in the mod, not the game misreporting.

Thanks, I had no idea this was an issue. Turns out this was linked to lobbies being marked as public, which I've now disabled for official servers: c5fa7da59c0562cff07c1e42ab12969806a05c4e

**Comment by rcelyte** [comment]
Great, that fixed it!

Another small note: the website doesn't display IPv6 endpoints correctly.
bssb

**Comment by roydejong** [comment]
Thanks again. I've decided to remove this part of the code altogether in d9eb555, as the check is no longer needed. We'll use the master-server reported value in all scenarios now.

**Pull request closed without merging**
